### ISSUE TITLE
CoreSchemaFilters.php on line 16

### ISSUE THREAD

**Issue by Hansanghyeon** [AxeWP/wp-graphql-rank-math#1]
### Description

Uncaught Error: Interface "AxeWP\GraphQL\Interfaces\Hookable" not found

### Steps to reproduce

1. download release zip
2. plugin install wordpress
3. enable plugin

```
 Fatal error: Uncaught Error: Interface "AxeWP\GraphQL\Interfaces\Hookable" not found
in /var/www/html/wp-content/plugins/wp-graphql-rank-math-develop/src/CoreSchemaFilters.php on line 16

Call stack:

include()
wp-content/plugins/ame-branding-add-on/vendor/composer/ClassLoader.php:480
Composer\A\includeFile()
wp-content/plugins/ame-branding-add-on/vendor/composer/ClassLoader.php:346
Composer\A\ClassLoader::loadClass()
wp-content/plugins/wp-graphql-rank-math-develop/src/Main.php:79
WPGraphQL\R\Main::setup()
wp-content/plugins/wp-graphql-rank-math-develop/src/Main.php:38
WPGraphQL\R\Main::instance()
wp-content/plugins/wp-graphql-rank-math-develop/wp-graphql-rank-math.php:108
graphql_seo_init()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-content/plugins/wp-graphql/src/WPGraphQL.php:256
WPGraphQL::{closure}()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-settings.php:576
require_once()
wp-config.php:133
require_once()
wp-load.php:50
require_once()
wp-admin/admin.php:34
require_once()
wp-admin/plugins.php:10
Query Monitor
```

### Plugin Version

0.0.2

### WordPress Version

6.0.1

### WPGraphQL Version

1.8.6

### Additional enviornmental details

PHP 8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for RankMath SEO, WPGraphQL, and WPGraphQL for Rank Math

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @Hansanghyeon thanks for taking the time to report this!

Are you sure you grabbed the release zip, and not the branch zip? I see the plugin path is `wp-graphql-rank-math-develop`.

What happens if you open up that directory and run `composer install --no-dev --optimize-autoloader`?

**Comment by Hansanghyeon** [comment]
@justlevine 
Thanks, I am able to test the plugin. 👍
