### ISSUE TITLE
Missing field in allowed fields makes field null when user not logged in

### ISSUE THREAD

**Issue by marziolek** [AxeWP/wp-graphql-rank-math#100]
https://github.com/AxeWP/wp-graphql-rank-math/blob/9fd2f1cc7026a029493b172eb2be1cb30948a12a/src/Model/Seo.php#L80

**Comment by justlevine** [comment]
Hey @marziolek I'm travellng, and you kinda just threw out the GH issue template that helps speed along triage.

Can you start by specifying which field (and on which GraphQL object - the class you shared is an abstract model shared by several SeoObject types) you believe is missing and should be available to unauthenticated users?

**Comment by marziolek** [comment]
@justlevine sorry about that. Dropped it too quickly. Amazing that you responded that fast!
When making this query in Graphql IDE
`query SEOData {
  nodeByUri(uri: "/portfolio") {
    ... on NodeWithRankMathSeo {
      seo {
        canonicalUrl
      }
    }
  }
}`
canonicalUrl field is always null, unless you switch to logged-in user.
![image](https://github.com/user-attachments/assets/a965b74a-4fbc-48fb-af45-119370f7f448)
When added canonicalUrl to fields mentioned above it worked every time.
