### ISSUE TITLE
Data on frontend not aligning with WPGraphiQL query

### ISSUE THREAD

**Issue by 2-fly-4-ai** [AxeWP/wp-graphql-rank-math#19]
### Description

When different URLS are used for Wp Adress URL and  site adress the data being returned no longer aligns with the WPGRAPHQL Ide

### Steps to reproduce

Create a backend on a subdomain.

Wp Adress URL should be backend subdomain. ie backend.sitename.com
Site Adress should be set to a different frontend site adress. 

Create  a custom post type. + a custom taxonomy for that post type. Enable Rankmath and set posts to no index.

Run Queries for SEO data. Meta Robots. Notice that the data being returned is wrong. Although it shows no-index in the WPGRAPHQL ide. The frontend says index for everything. 

The only thing that fixes this issue is changing both urls to the same. Although this is not an acceptable solution to the problem as the frontend URL needs to be different in my use case and other headless use cases. 

The same goes for the other data such as breadcrumbs, title etc. Other page data related to the Rankmath SEO query is also missing, some is there though(graphql IDE) but when queried it will show incorrect data on the frontend. 

Example

"canonicalUrl": null,
        "robots": [
          "follow",
          "noindex"
        ],

The frontend data will show something different. 

### Plugin Version

0.0.7 and others

### WordPress Version

WordPress 6.1.1 running Twenty Twenty-One theme.

### WPGraphQL Version

Version 1.13.7

### RankMath SEO Version

Version 1.0.103.1 + pro Version 3.0.25

### Additional enviornmental details

Running on next.js with apollo client

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for RankMath SEO, WPGraphQL, and WPGraphQL for Rank Math

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
@2-fly-4-ai I merged #23 because I wanted to get these fixes upstream as fast as possible. If there's still something that's not resolving correctly, let me know and I'll reopen.
