### ISSUE TITLE
Robot meta data showing noindex and nofollow for all pages and posts

### ISSUE THREAD

**Issue by nynrathod** [AxeWP/wp-graphql-rank-math#41]
### Description

Hi all, I am trying get robots meta data in rank math wpgraphql plugin, but seems like all results showing noindex and nofollow for all pages and posts. I check in my rank match setting, and almost all pages have index property, still wpgraphql showing noindex and nofollow

### Steps to reproduce

Go to graphql IDE, and add this query:
```
query myQuery {
  contentNodes(first: 999) {
    edges {
      node {
        seo {
          robots
        }
      }
    }
  }
}
```

### Additional Context

I disabled discourage search enginer in settings > reading, but still it is showing noindex and nofollow

### Plugin Version

0.0.11

### WordPress Version

6.1.1

### WPGraphQL Version

1.14.0

### RankMath SEO Version

1.0.110.2 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for RankMath SEO, WPGraphQL, and WPGraphQL for Rank Math

- [ ] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
@nynrathod 

I am unable to replicate this issue.

This is from a default WP instance (via `composer install-test-env`), with the only change made to the robots on the default Hello World post.
![image](https://user-images.githubusercontent.com/29322304/230461625-c8a72f82-8d24-42c2-916a-f38185b869b4.png)

![image](https://user-images.githubusercontent.com/29322304/230461747-bd7cb874-f4e4-41f7-a015-fbbac9c4fe20.png)

Then for good measure I added  a new `nofollow` post, and things are still working:

![image](https://user-images.githubusercontent.com/29322304/230462681-2e3872f5-d421-4ea6-a409-07e9aa65f2c2.png)

First, please confirm that this issue persists with **ALL plugins disabled except for RankMath SEO, WPGraphQL, and WPGraphQL for Rank Math** (you skipped this in the issue report).

Then, please provide me whatever additional information you can. Best would be to create a _replicable test case_, meaning start with a clean site, confirm it works, and then start changing the config until you see the bug appear, and share the steps).

**Comment by justlevine** [comment]
Hi @nynrathod - were you able to pinpoint the source of this issue?

**Comment by justlevine** [comment]
Hey @nynrathod I havn't heard from you, so I'm going to close this out. If you're still struggling with this let me know, and I'll reopen it.
