### ISSUE TITLE
productData inside openGraph is returning null as value

### ISSUE THREAD

**Issue by joanpzen** [AxeWP/wp-graphql-rank-math#66]
### Description

https://www.zenbusiness.com/llc/

I did a console log of the openGraph props in Astro: and articleMeta & videoMeta comes with info, but productMeta doesn’t.
<img width="928" alt="image" src="https://github.com/AxeWP/wp-graphql-rank-math/assets/104439876/27ee970d-a0a3-4264-bf04-8ef6bee40e0b">

### Steps to reproduce

This is the schema of one of the pages we are checking:
<img width="1612" alt="image" src="https://github.com/AxeWP/wp-graphql-rank-math/assets/104439876/2dfcadaf-4fc7-41e1-af3a-297ab08ad13e">

This is the part of the code always returning empty:
<img width="1551" alt="image" src="https://github.com/AxeWP/wp-graphql-rank-math/assets/104439876/f7e1464e-1ecb-4354-876b-b3f00cfa39be">

### Plugin Version

0.0.14

### WordPress Version

6.3.2

### WPGraphQL Version

1.19.0

### RankMath SEO Version

1.0.208.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for RankMath SEO, WPGraphQL, and WPGraphQL for Rank Math

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Thanks for the report, @joanpzen and the sample data! I'll test it over the weekend.

In the meantime, I see you're using v0.0.14 of the plugin. Does updating to the [latest](https://github.com/AxeWP/wp-graphql-rank-math/releases)(v0.0.**16** at time of writing), solve things for you?

Iirc there were some breaking API changes made in Rank Math 1.0.201+ we had to add compatibility for (and you're at 1.0.208)

**Comment by justlevine** [comment]
Hey @joanpzen (and team),

Despite multiple attempts over the last month, I've still been unable to replicate your particular issues (re [slack](https://wp-graphql.slack.com/archives/C03SBS7SR8F/p1704810894125539).

While I'm able to replicate the original issue on the latest release, #69 indeed fixes it on my local tests, even with RM Pro's schema builder.

I've merged that PR, and will keep this issue open in the hopes that you're able to provide additional replication steps 🤞

---

1. ![image](https://github.com/AxeWP/wp-graphql-rank-math/assets/29322304/18d838c4-974c-4e33-9227-d15dd381fca9)

2. ![image](https://github.com/AxeWP/wp-graphql-rank-math/assets/29322304/6a386151-63c2-4f7c-b7bb-aecb126ad59f)

And `page.seo.fullHead` shows both the OG `meta` tags _and_ the JSON LD schema object:


`fullHead: "<meta name=\"description\" content=\"Social description\"/>\n<meta name=\"robots\" content=\"noindex, nofollow\"/>\n<meta property=\"og:locale\" content=\"en_US\" />\n<meta property=\"og:type\" content=\"article\" />\n<meta property=\"og:title\" content=\"Custom product schema - WPTest\" />\n<meta property=\"og:description\" content=\"Some description\" />\n<meta property=\"og:url\" content=\"https://wptest.dvl.to/custom-product-schema/\" />\n<meta property=\"og:site_name\" content=\"WPTest\" />\n<meta property=\"og:updated_time\" content=\"2024-03-02T08:10:28+00:00\" />\n<meta property=\"article:published_time\" content=\"2024-03-02T07:43:53+00:00\" />\n<meta property=\"article:modified_time\" content=\"2024-03-02T08:10:28+00:00\" />\n<meta property=\"product:brand\" content=\"AxePress\" />\n<meta property=\"product:price:amount\" content=\"999\" />\n<meta name=\"twitter:card\" content=\"summary_large_image\" />\n<meta name=\"twitter:title\" content=\"Custom product schema - WPTest\" />\n<meta name=\"twitter:description\" content=\"Some description\" />\n<meta name=\"twitter:label1\" content=\"Time to read\" />\n<meta name=\"twitter:data1\" content=\"Less than a minute\" />\n<script type=\"application/ld+json\" class=\"rank-math-schema-pro\">{\"@context\":\"https://schema.org\",\"@graph\":[{\"@type\":[\"Person\",\"Organization\"],\"@id\":\"https://wptest.dvl.to/#person\",\"name\":\"WPTest\"},{\"@type\":\"WebSite\",\"@id\":\"https://wptest.dvl.to/#website\",\"url\":\"https://wptest.dvl.to\",\"name\":\"WPTest\",\"publisher\":{\"@id\":\"https://wptest.dvl.to/#person\"},\"inLanguage\":\"en-US\"},{\"@type\":\"ItemPage\",\"@id\":\"https://wptest.dvl.to/custom-product-schema/#webpage\",\"url\":\"https://wptest.dvl.to/custom-product-schema/\",\"name\":\"Custom product schema - WPTest\",\"datePublished\":\"2024-03-02T07:43:53+00:00\",\"dateModified\":\"2024-03-02T08:10:28+00:00\",\"isPartOf\":{\"@id\":\"https://wptest.dvl.to/#website\"},\"inLanguage\":\"en-US\"},{\"@type\":\"Person\",\"@id\":\"https://wptest.dvl.to/author/admin/\",\"name\":\"admin\",\"url\":\"https://wptest.dvl.to/author/admin/\",\"image\":{\"@type\":\"ImageObject\",\"@id\":\"https://secure.gravatar.com/avatar/9e445d9280397ce7e814a355d4aa98ae?s=96&amp;d=mm&amp;r=g\",\"url\":\"https://secure.gravatar.com/avatar/9e445d9280397ce7e814a355d4aa98ae?s=96&amp;d=mm&amp;r=g\",\"caption\":\"admin\",\"inLanguage\":\"en-US\"},\"sameAs\":[\"https://wptest.dvl.to\"]},{\"headline\":\"Custom product schema - WPTest\",\"description\":\"Social description\",\"speakable\":{\"@type\":\"SpeakableSpecification\",\"cssSelector\":[]},\"@type\":\"BlogPosting\",\"author\":{\"@id\":\"https://wptest.dvl.to/author/admin/\",\"name\":\"admin\"},\"datePublished\":\"2024-03-02T07:43:53+00:00\",\"dateModified\":\"2024-03-02T08:10:28+00:00\",\"name\":\"Custom product schema - WPTest\"},{\"@type\":\"Product\",\"name\":\"Custom product schema - WPTest\",\"url\":\"https://wptest.dvl.to/custom-product-schema/\",\"description\":\"Social description\",\"sku\":\"MySKU\",\"brand\":{\"@type\":\"Brand\",\"name\":\"AxePress\"},\"offers\":{\"@type\":\"Offer\",\"url\":\"https://wptest.dvl.to/custom-product-schema/\",\"price\":\"999\",\"availability\":\"InStock\",\"currency\":\"USD\"},\"mainEntityOfPage\":{\"@id\":\"https://wptest.dvl.to/custom-product-schema/#webpage\"}}]}</script>\n",`

**Comment by justlevine** [comment]
Haven't heard anything for a while, so I'm going to close this out. If you're still experiencing this issue, let us know and we'll get this reopened ).
