### ISSUE TITLE
Fallback to page URL when canonicalUrl field is null

### ISSUE THREAD

**Issue by ariel-integrity** [AxeWP/wp-graphql-rank-math#93]
### What problem does this address?

Pulling canonicalUrl and getting the default value (when not set by WP admin user) sets developer up for simple implementation.

### What is your proposed solution?

Fallback to page URL when canonicalUrl field is null, make available in WPGraphQL queries

### What alternatives have you considered?

Setting up canonical to be page URL by default within next, have it overridden if the field pulled by WPGraphQL Rank Math plugin is not null.

**Comment by justlevine** [comment]
Hey @ariel-integrity ,

I'm unable to replicate this. Perhaps you can provide more specific information about your setup + replication steps?

---

1. Create a new post or page. (Note how the canonical URL is greyed out, the text there is just the placeholder).

![image](https://github.com/AxeWP/wp-graphql-rank-math/assets/29322304/19598a1d-18c2-4e21-80d2-ed3644a1410f)

2. Query posts for `canonicalUrl`

```graphql
query MyQuery {
  contentNodes {
    nodes {
      ... on Post {
        seo {
          ... on RankMathPostObjectSeo{
            canonicalUrl
          }
        }
      }
    }
  }
}
```
3. See results.
![image](https://github.com/AxeWP/wp-graphql-rank-math/assets/29322304/d09b2dff-f14c-45bd-b3ee-f09a63163263)

**Comment by justlevine** [comment]
Hey @ariel-integrity, 
It's been quiet for a few weeks, so I'm going to assume you've figured this out and close out this ticket.

If you're still experiencing this issue, please respond with some replication steps, and I'll reopen this and take a look.
